### PR TITLE
Implement dev env with Docker

### PR DESCRIPTION
**Pull request by sauloperez**
## Context

I think I came to put some sense an all the docker config files scattered throughout the project. At a glance, it's very hard to know what's used, what's maintained and what's not. 

First, as per https://www.sharetribe.com/community/t/docker-compose-run-error-in-localhost/599/8, current (as of 2017) Docker support is not 100% suitable for running open-source Sharetribe.

Then, with https://www.sharetribe.com/community/t/locate-docker-file-for-development/835/2 I could confirm Docker isn’t used for development, the Docker file is only for production. For the record, the existing docker files are meant to be run as `docker-compose -f docker-compose.yml -f docker-compose.app.yml up -d`.

But it turns out, they implemented Docker for development in the early days with `fig.yml`. Fig is what became `docker-compose` later on. However, that config was not maintained but serves quite well as inspiration as most of the things haven't changed that much.

## Solution

With all that, I decided the best option I had was to pick all that know-how described above plus OFN's docker and start a new development docker-compose and Dockerfile (I couldn't find any docker for dev out there:man_shrugging: ).

Starting from scratch seemed like the safest bet after trying `docker-compose -f fig.yml`. It kind of worked but the old and deprecated settings there were a trap. Note that most of the stuff was reused from the production files and I just had to remove lines.

Doing it this way makes go through each of the things they implemented to set up a production instance, which is great to understand the product.

### CODE REVIEW

**Comment by enricostano** [comment]
Nice idea, and what a mess are unmaintened configs/tools for development :see_no_evil: 

In any case, I'm just struggling to understand why we don't just ignore docker and do what we generally do with Ansible playbooks. If we cannot use the same `Dockerfile` for dev and prod... then I would avoid it and just use old school Ansible playbooks. #my2cents

**Comment by sauloperez** [comment]
What I wanted to avoid is to start exactly from scratch and my goal initially, was to make the existing docker work.

As I explained in the description, it was just a matter of copying the production setup and remove a bunch of production-related settings. And now, I kind of guess how assets are working in production but that was probably pure luck :trollface:

It would be ace to open a PR upstream and ask them to maintain this setup once we have fully working.

**Comment by enricostano** [comment]
> What I wanted to avoid is to start exactly from scratch

Is [this](https://github.com/coopdevs/donalo/) not working for development? We're using it for `next` environment right now, right?

**Comment by sauloperez** [comment]
exactly, that's the production set up only and as you know, there are a couple of things still missing.

In any case, I'm not marrying anything I just need the time to understand and explore things, and one of those was setting up the development environment. Configuring the app for our use case is taking too long without it. We came to a point where the dev env is a must. Later, once all is understood, we can merge provisioning strategies based on more informed decisions.

**Review by danypr92 — APPROVED** [review]
I understand the reason for this PR. We need a development environment to agile the customization of this app. And I agree with this reason. I understand why we don't start from scratch an Ansible project to set the development environment, if Sharetripe uses docker in production, we can adapt this docker to up a development environment.

I was following the commits to understand the Dockerfile things... Sorry, but I can't help in these steps, because I don't have experience with Dockerfiles, but I am excited to start to develop with Docker! :D

**Comment by sauloperez** [comment]
Thanks for understanding, guys.

**Pull request merged**
